import { SpeciesData } from './species';

export const extendedSpecies: SpeciesData[] = [
  { name: 'Tiger Shark', scientificName: 'Galeocerdo cuvier', variant: 'Apex Predator', depth: [0.0, 0.15], size: 45, type: 'tetra', lum: 0, agg: 85, desc: 'A large, solitary, mostly nocturnal hunter known for its dark stripes.', habitat: 'Coastal and pelagic waters', ecology: 'Often called the "garbage can of the sea" due to its varied diet.', traits: [{name: 'Markings', value: 'Tiger tracks fade with age'}, {name: 'Teeth', value: 'Serrated and recurved'}], location: 'Global tropical waters', baseSpeed: 3.0, color: 'rgba(100, 110, 120, 0.9)', imageUrl: 'https://images.unsplash.com/photo-1560275619-4662e36fa65c?auto=format&fit=crop&w=800&q=80' },
  { name: 'Whale Shark', scientificName: 'Rhincodon typus', variant: 'Filter Feeder', depth: [0.0, 0.2], size: 90, type: 'flat', lum: 0, agg: 5, desc: 'The largest known extant fish species, a slow-moving filter-feeding carpet shark.', habitat: 'Open waters of the tropical oceans', ecology: 'Feeds almost exclusively on plankton and small fishes, completely harmless to humans.', traits: [{name: 'Mouth', value: 'Up to 1.5m wide'}, {name: 'Pattern', value: 'Unique spots and stripes'}], location: 'Global tropical oceans', baseSpeed: 1.5, color: 'rgba(50, 70, 90, 0.9)', imageUrl: 'https://images.unsplash.com/photo-1544552866-d3ed42536fcb?auto=format&fit=crop&w=800&q=80' },
  { name: 'Blue Marlin', scientificName: 'Makaira nigricans', variant: 'Pelagic Predator', depth: [0.0, 0.1], size: 38, type: 'tetra', lum: 0, agg: 65, desc: 'One of the biggest fish in the world, known for its long, lethal bill.', habitat: 'Tropical and subtropical open oceans', ecology: 'Uses its bill to stun, injure, or kill schooling fish.', traits: [{name: 'Top Speed', value: '80 km/h'}, {name: 'Bill Length', value: '20% of total length'}], location: 'Atlantic, Pacific, Indian Oceans', baseSpeed: 6.0, color: 'rgba(40, 80, 200, 0.9)', imageUrl: 'https://images.unsplash.com/photo-1596489370607-bf3648ed9de2?auto=format&fit=crop&w=800&q=80' },
  { name: 'Lionfish', scientificName: 'Pterois', variant: 'Venomous Reef', depth: [0.0, 0.1], size: 10, type: 'tetra', lum: 5, agg: 40, desc: 'A stunning but highly invasive species with red, white, and black bands.', habitat: 'Coral reefs and rocky crevices', ecology: 'An aggressive predator with venomous spiky fin rays.', traits: [{name: 'Toxicity', value: 'Highly venomous spines'}, {name: 'Invasive', value: 'Major threat in Atlantic'}], location: 'Indo-Pacific (Native), Atlantic (Invasive)', baseSpeed: 1.0, color: 'rgba(200, 50, 50, 0.9)', imageUrl: 'https://images.unsplash.com/photo-1524704796725-9fc3044a58b2?auto=format&fit=crop&w=800&q=80' },
  { name: 'Swordfish', scientificName: 'Xiphias gladius', variant: 'Billfish', depth: [0.0, 0.3], size: 30, type: 'tetra', lum: 0, agg: 60, desc: 'Large, highly migratory, predatory fish characterized by a long, flat, pointed bill.', habitat: 'Epipelagic and Mesopelagic zones', ecology: 'They use their "sword" to slash at schools of prey, severing or stunning them.', traits: [{name: 'Eye Heating', value: 'Special tissue warms brain'}, {name: 'Migration', value: 'Follows diurnal vertical migration'}], location: 'Global tropical/temperate waters', baseSpeed: 5.5, color: 'rgba(100, 120, 150, 0.9)', imageUrl: 'https://images.unsplash.com/photo-1596489370607-bf3648ed9de2?auto=format&fit=crop&w=800&q=80' },
  { name: 'Barracuda', scientificName: 'Sphyraena', variant: 'Ambush Predator', depth: [0.0, 0.05], size: 15, type: 'tetra', lum: 0, agg: 75, desc: 'Ray-finned fish known for their large size, fearsome appearance, and ferocious behavior.', habitat: 'Coral reefs and seagrass beds', ecology: 'Relies on surprise and short bursts of incredible speed to overrun prey.', traits: [{name: 'Dentition', value: 'Fang-like teeth'}, {name: 'Speed', value: 'Intense short bursts'}], location: 'Global tropical oceans', baseSpeed: 4.5, color: 'rgba(180, 180, 190, 0.9)', imageUrl: 'https://images.unsplash.com/photo-1522069213506-c87cdbafe2df?auto=format&fit=crop&w=800&q=80' },
  { name: 'Moray Eel', scientificName: 'Muraenidae', variant: 'Crevice Hunter', depth: [0.0, 0.15], size: 18, type: 'tetra', lum: 0, agg: 55, desc: 'Cosmopolitan family of eels known for lurking in reef crevices.', habitat: 'Shallow water coral reefs', ecology: 'Night-time ambush predators with a second set of "pharyngeal jaws".', traits: [{name: 'Jaws', value: 'Pharyngeal (Alien-like)'}, {name: 'Skin', value: 'Scaleless, thick mucus layer'}], location: 'Worldwide reefs', baseSpeed: 2.0, color: 'rgba(120, 100, 80, 0.9)', imageUrl: 'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?auto=format&fit=crop&w=800&q=80' },
  { name: 'Green Sea Turtle', scientificName: 'Chelonia mydas', variant: 'Marine Reptile', depth: [0.0, 0.05], size: 25, type: 'ray', lum: 0, agg: 5, desc: 'A large, heavy sea turtle with a wide, smooth carapace.', habitat: 'Tropical and subtropical coasts', ecology: 'Primarily herbivorous as adults, grazing on seagrasses.', traits: [{name: 'Diet', value: 'Strictly herbivorous adult'}, {name: 'Migration', value: 'Thousands of miles'}], location: 'Global oceans', baseSpeed: 1.5, color: 'rgba(50, 150, 50, 0.8)', imageUrl: 'https://images.unsplash.com/photo-1544552866-d3ed42536fcb?auto=format&fit=crop&w=800&q=80' },
  { name: 'Moorish Idol', scientificName: 'Zanclus cornutus', variant: 'Reef Dweller', depth: [0.0, 0.02], size: 6, type: 'tetra', lum: 0, agg: 10, desc: 'A distinctly striped, highly recognizable marine fish.', habitat: 'Shallow reefs and lagoons', ecology: 'Feeds heavily on benthic invertebrates and sponges.', traits: [{name: 'Dorsal Fin', value: 'Extremely elongated sickle'}, {name: 'Diet', value: 'Sponge specialist'}], location: 'Tropical Indo-Pacific', baseSpeed: 1.2, color: 'rgba(200, 200, 200, 0.9)', imageUrl: 'https://images.unsplash.com/photo-1524704796725-9fc3044a58b2?auto=format&fit=crop&w=800&q=80' },
  { name: 'Red Lionfish', scientificName: 'Pterois volitans', variant: 'Venomous Predator', depth: [0.05, 0.15], size: 9, type: 'tetra', lum: 5, agg: 45, desc: 'Distinctive stripes and venomous spines make it a beautiful but deadly sight.', habitat: 'Coral reefs and hard bottom habitats', ecology: 'Highly successful invasive ambush predator.', traits: [{name: 'Spines', value: '13 venomous dorsal rays'}, {name: 'Hunting', value: 'Blows water jets to disorient prey'}], location: 'Indo-Pacific, Caribbean', baseSpeed: 0.8, color: 'rgba(180, 50, 50, 0.9)', imageUrl: 'https://images.unsplash.com/photo-1524704796725-9fc3044a58b2?auto=format&fit=crop&w=800&q=80' },
  
  // Mesopelagic additions
  { name: 'Stoplight Loosejaw', scientificName: 'Malacosteus niger', variant: 'Deep Sea Predator', depth: [0.2, 0.6], size: 10, type: 'tetra', lum: 60, agg: 65, desc: 'A deep-sea dragonfish that emits red bioluminescence to hunt.', habitat: 'Mesopelagic zone', ecology: 'Uses a red bioluminescent searchlight that its prey cannot see.', traits: [{name: 'Vision', value: 'Can see far red light'}, {name: 'Jaws', value: 'Bottomless lower jaw'}], location: 'Global deep oceans', baseSpeed: 1.2, color: 'rgba(50, 10, 10, 0.9)', imageUrl: 'https://images.unsplash.com/photo-1545671913-b89ac1b4ac10?auto=format&fit=crop&w=800&q=80' },
  { name: 'Fangtooth', scientificName: 'Anoplogaster cornuta', variant: 'Abyssal Nightmare', depth: [0.3, 0.8], size: 8, type: 'flat', lum: 0, agg: 80, desc: 'Has the largest teeth of any fish in the ocean, proportionate to body size.', habitat: 'Bathypelagic and Mesopelagic', ecology: 'Lurks in the darkness, detecting prey through chemoreception.', traits: [{name: 'Teeth', value: 'Requires socket in brain to close mouth'}, {name: 'Armor', value: 'Thick, hard mucosal scales'}], location: 'Global deep oceans', baseSpeed: 1.0, color: 'rgba(30, 30, 30, 0.9)', imageUrl: 'https://images.unsplash.com/photo-1618477461853-cf6ed80f04c0?auto=format&fit=crop&w=800&q=80' },
  { name: 'Snipe Eel', scientificName: 'Nemichthyidae', variant: 'Thread Eater', depth: [0.3, 0.7], size: 12, type: 'tetra', lum: 0, agg: 15, desc: 'An extremely slender, thread-like eel with a beak curving outwards.', habitat: 'Mesopelagic and Bathypelagic zones', ecology: 'Sweeps its open beak through the water to entangle crustacean antennae.', traits: [{name: 'Body Shape', value: 'Thread-like, up to 1m long'}, {name: 'Beak', value: 'Outward curving jaws'}], location: 'All oceans', baseSpeed: 0.5, color: 'rgba(100, 100, 100, 0.6)', imageUrl: 'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?auto=format&fit=crop&w=800&q=80' },
  { name: 'Barreleye Fish', scientificName: 'Macropinna microstoma', variant: 'Transparent Dome', depth: [0.3, 0.6], size: 6, type: 'tetra', lum: 15, agg: 10, desc: 'A deeply weird fish with a transparent head and tubular eyes.', habitat: 'Mesopelagic zone', ecology: 'Looks straight up through its transparent skull to silhouette prey against surface light.', traits: [{name: 'Head', value: 'Fluid-filled transparent shield'}, {name: 'Eyes', value: 'Tubular, rotatable inward'}], location: 'North Pacific', baseSpeed: 0.6, color: 'rgba(50, 80, 50, 0.8)', imageUrl: 'https://images.unsplash.com/photo-1535591273668-578e31182c4f?auto=format&fit=crop&w=800&q=80' },
  { name: 'Lanternfish', scientificName: 'Myctophidae', variant: 'Bioluminescent Swarm', depth: [0.2, 0.5], size: 3, type: 'tetra', lum: 80, agg: 5, desc: 'One of the most abundant vertebrates on Earth, glittering with photophores.', habitat: 'Mesopelagic zone', ecology: 'Crucial prey species forming the "deep scattering layer" detected by sonar.', traits: [{name: 'Photophores', value: 'Species-specific lighting'}, {name: 'Biomass', value: '65% of deep sea fish biomass'}], location: 'Global oceans', baseSpeed: 1.0, color: 'rgba(150, 150, 200, 0.8)', imageUrl: 'https://images.unsplash.com/photo-1522069213506-c87cdbafe2df?auto=format&fit=crop&w=800&q=80' },
  
  // Abyssal/Hadal
  { name: 'Pelican Eel', scientificName: 'Eurypharynx pelecanoides', variant: 'Gulper Variant', depth: [0.5, 0.9], size: 14, type: 'tetra', lum: 20, agg: 40, desc: 'A deep-sea eel equipped with a massive, pelican-like pouch mouth.', habitat: 'Bathypelagic and Abyssopelagic zones', ecology: 'Can swallow prey much larger than itself, turning into a balloon.', traits: [{name: 'Mouth', value: 'Expandable throat pouch'}, {name: 'Tail', value: 'Luminous lure at tip'}], location: 'Global tracking', baseSpeed: 0.6, color: 'rgba(40, 40, 50, 0.9)', imageUrl: 'https://images.unsplash.com/photo-1545671913-b89ac1b4ac10?auto=format&fit=crop&w=800&q=80' },
  { name: 'Tripod Fish', scientificName: 'Bathypterois grallator', variant: 'Benthic Walker', depth: [0.6, 1.0], size: 8, type: 'flat', lum: 0, agg: 5, desc: 'Uses immensely elongated fin rays to "stand" on the deep sea mud.', habitat: 'Abyssal plains', ecology: 'Stands facing the current, waiting blindly for zooplankton to bump into its fins.', traits: [{name: 'Fins', value: 'Rigid tripod stilts (1m long)'}, {name: 'Hermaphrodite', value: 'Can self-fertilize if solitary'}], location: 'Global abyssal plains', baseSpeed: 0.2, color: 'rgba(80, 80, 90, 0.8)', imageUrl: 'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?auto=format&fit=crop&w=800&q=80' },
  { name: 'Giant Isopod', scientificName: 'Bathynomus giganteus', variant: 'Deep Sea Scavenger', depth: [0.5, 0.8], size: 7, type: 'flat', lum: 0, agg: 20, desc: 'A massive crustacean resembling a pillbug, demonstrating deep-sea gigantism.', habitat: 'Benthic zones, Bathypelagic floors', ecology: 'Voracious scavenger of whale falls and dead fish on the ocean floor.', traits: [{name: 'Gigantism', value: 'Grows up to 50cm long'}, {name: 'Metabolism', value: 'Can survive years without food'}], location: 'Cold deep basins', baseSpeed: 0.4, color: 'rgba(200, 180, 160, 0.9)', imageUrl: 'https://images.unsplash.com/photo-1544552866-d3ed42536fcb?auto=format&fit=crop&w=800&q=80' },
  { name: 'Black Swallower', scientificName: 'Chiasmodon niger', variant: 'Glutton Variant', depth: [0.4, 0.8], size: 4, type: 'tetra', lum: 0, agg: 50, desc: 'A small fish capable of swallowing meals 10 times its own mass.', habitat: 'Mesopelagic and Bathypelagic zones', ecology: 'Often dies from swallowing fish so large that they decompose before digestion.', traits: [{name: 'Stomach', value: 'Extreme distention capacity'}, {name: 'Teeth', value: 'Hinged, trap-door teeth'}], location: 'Global deep oceans', baseSpeed: 0.5, color: 'rgba(20, 20, 20, 0.9)', imageUrl: 'https://images.unsplash.com/photo-1618477461853-cf6ed80f04c0?auto=format&fit=crop&w=800&q=80' },
  { name: 'Sixgill Shark', scientificName: 'Hexanchus griseus', variant: 'Prehistoric Predator', depth: [0.3, 0.7], size: 45, type: 'tetra', lum: 0, agg: 75, desc: 'A primitive deep water shark that retains traits from the Triassic period.', habitat: 'Continental shelves and underwater canyons', ecology: 'Nighttime vertical migrator, scavenging and hunting in absolute darkness.', traits: [{name: 'Gills', value: 'Six pairs (primitive trait)'}, {name: 'Eyes', value: 'Fluorescent green glow'}], location: 'Global deep shelves', baseSpeed: 2.0, color: 'rgba(90, 80, 70, 0.9)', imageUrl: 'https://images.unsplash.com/photo-1560275619-4662e36fa65c?auto=format&fit=crop&w=800&q=80' },
  { name: 'Colossal Squid', scientificName: 'Mesonychoteuthis hamiltoni', variant: 'Abyssal Titan', depth: [0.5, 0.95], size: 60, type: 'squid', lum: 20, agg: 85, desc: 'Heavier and shorter than the Giant Squid, equipped with swiveling hooks.', habitat: 'Antarctic deep waters', ecology: 'Fiercely combats sperm whales in the freezing abyss.', traits: [{name: 'Tentacles', value: 'Rotating barbed hooks'}, {name: 'Eyes', value: 'Size of soccer balls'}], location: 'Circumantarctic oceans', baseSpeed: 4.0, color: 'rgba(150, 40, 40, 0.9)', imageUrl: 'https://images.unsplash.com/photo-1545671913-b89ac1b4ac10?auto=format&fit=crop&w=800&q=80' },
  { name: 'Sperm Whale', scientificName: 'Physeter macrocephalus', variant: 'Mammalian Titan', depth: [0.0, 0.8], size: 100, type: 'flat', lum: 0, agg: 50, desc: 'The largest toothed predator on Earth, plunging miles deep to hunt squid.', habitat: 'Global open ocean', ecology: 'Uses advanced echolocation ("clicks") to stun and locate giant squid.', traits: [{name: 'Diving', value: 'Over 2 hours on one breath'}, {name: 'Brain', value: 'Largest known of any animal'}], location: 'Ice-free global oceans', baseSpeed: 5.0, color: 'rgba(60, 60, 70, 0.9)', imageUrl: 'https://images.unsplash.com/photo-1544552866-d3ed42536fcb?auto=format&fit=crop&w=800&q=80' }
];
